#include "updater.h"

#include <QCoreApplication>
#include <QEventLoop>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QProcess>
#include <QTimer>

#include <cstring>

#include "device_paths.h"
#include "inkview_bridge.h"
#include "update_log.h"
#include "miniz.h"

extern "C" {
#include "daemon.h"
#include "version.h"
}

namespace {

constexpr const char *kApiUrl =
    "https://api.github.com/repos/winst0niuss/pocketbook-statistics/releases/latest";
/* The full list, newest first, including pre-releases — which /latest omits by
 * design. Only devices carrying the opt-in file below ever ask for it. */
constexpr const char *kApiListUrl =
    "https://api.github.com/repos/winst0niuss/pocketbook-statistics/releases?per_page=10";
/* Touch this file on a device to put it on the pre-release channel. It is a
 * marker, not a setting: nothing in the app creates it, so a reader that has
 * not been opted in by hand can never be offered a release candidate. */
constexpr const char *kPrereleaseFlag = STATS_DIR "/prerelease";
constexpr const char *kAssetName = "PocketBookStatistics.zip";
constexpr const char *kUpdateDir = STATS_DIR "/update";
/* Anything smaller than this is a proxy error page, not our binary. */
constexpr qint64 kMinBinarySize = 300 * 1024;

QString updatePath(const char *name)
{
    return devicePath(kUpdateDir) + QLatin1Char('/') + QString::fromLatin1(name);
}

bool looksLikeElf(const QString &path)
{
    QFile f(path);
    if (!f.open(QIODevice::ReadOnly))
        return false;
    return f.read(4) == QByteArrayLiteral("\x7f" "ELF");
}

/* The handover: the running binary cannot overwrite itself, so a small shell
 * script waits for us to exit, stops the daemon (it runs from the same file),
 * swaps in the new binary and starts it again. */
QString handoverScript(const QString &app, const QString &staged)
{
    return QStringLiteral(
        "#!/bin/sh\n"
        "# Generated by the updater; runs after the app has exited.\n"
        "APP='%1'\n"
        "NEW='%2'\n"
        "i=0\n"
        "while [ $i -lt 30 ] && kill -0 %3 2>/dev/null; do\n"
        "    i=$((i+1))\n"
        "    sleep 1\n"
        "done\n"
        "DPID=$(cat '%4' 2>/dev/null)\n"
        "[ -n \"$DPID\" ] && kill \"$DPID\" 2>/dev/null\n"
        "sleep 1\n"
        "mv -f \"$NEW\" \"$APP\" || exit 1\n"
        "sync\n"
        "\"$APP\" &\n")
        .arg(app, staged)
        .arg(QCoreApplication::applicationPid())
        .arg(devicePath(PIDFILE));
}

} // namespace

Updater::Updater(QObject *parent) : QObject(parent)
{
    /* If we are running at all, the previous handover is over: its script did
     * its job or died trying. A staged .new is left alone — a failed swap
     * reports its path so the file can still be copied over by hand. */
    QFile::remove(updatePath("apply.sh"));
}

/* Only worth showing when the last run did not end in one of its resting
 * states — which includes the run that ended by taking the process with it. */
/* The tail of the log, for the screen to show when an update has failed. It
 * used to hide itself by looking at the last line and deciding whether the run
 * had come to rest — which stopped working the moment the app, the daemon and
 * the shim started writing to the same file, since the last line is then rarely
 * an update state at all. The screen decides now: it shows this only on error,
 * where the lines are worth the space. */
QString Updater::diagnostics() const
{
    return updateLogTail(8);
}

QString Updater::currentVersion() const
{
    return QStringLiteral(APP_VERSION);
}

void Updater::publish(const QString &state)
{
    updateLog(QStringLiteral("state: ") + state);
    state_ = state;
    emit changed();
    /* Let the scene repaint before the next blocking firmware call. User input
     * stays queued so a second tap cannot re-enter check()/install(). */
    QCoreApplication::processEvents(QEventLoop::ExcludeUserInputEvents);
}

void Updater::fail(const QString &key, const QString &detail)
{
    errorKey_ = key;
    errorDetail_ = detail;
    publish(QStringLiteral("error"));
}

bool Updater::download(const QString &url, const QString &dest, int timeoutSeconds,
                       bool retry)
{
    QDir().mkpath(devicePath(kUpdateDir));
    QFile::remove(dest);
    const int rc = inkViewDownload(url, dest, timeoutSeconds, retry);
    if (rc != 0) {
        fail(rc == kInkViewNetUnsupported ? QStringLiteral("update.errUnsupported")
                                          : QStringLiteral("update.errDownload"),
             inkViewNetErrorText(rc));
        return false;
    }
    return true;
}

void Updater::check()
{
    updateLog(QStringLiteral("check: pressed, running ")
              + QStringLiteral(APP_VERSION));
    errorKey_.clear();
    errorDetail_.clear();
    latestVersion_.clear();
    assetUrl_.clear();
    assetSize_ = 0;
    publish(QStringLiteral("connecting"));

    if (!inkViewNetworkUp()) {
        fail(QStringLiteral("update.errNoNetwork"));
        return;
    }

    updateLog(QStringLiteral("check: network is up"));
    publish(QStringLiteral("checking"));
    const bool prerelease = QFile::exists(devicePath(kPrereleaseFlag));
    if (prerelease)
        updateLog(QStringLiteral("check: pre-release channel"));
    const QString jsonPath = updatePath("latest.json");
    if (!download(QString::fromLatin1(prerelease ? kApiListUrl : kApiUrl), jsonPath,
                  kCheckTimeoutSeconds, false))
        return;

    QFile f(jsonPath);
    if (!f.open(QIODevice::ReadOnly)) {
        fail(QStringLiteral("update.errResponse"));
        return;
    }
    const QJsonDocument doc = QJsonDocument::fromJson(f.readAll());
    f.close();
    QFile::remove(jsonPath);

    /* /latest answers with one release; the list answers with an array — and
     * that array is not in date order. GitHub sorts it by tag name as text, so
     * a run of candidates comes back as rc9, rc8 … rc2, rc11, rc10, rc1: the
     * two newest sit in the middle, and taking the head offered a device on
     * rc9 its own version and called it up to date. Compare them instead and
     * keep the highest. */
    QJsonObject release;
    if (doc.isObject()) {
        release = doc.object();
    } else if (doc.isArray()) {
        for (const QJsonValue &value : doc.array()) {
            const QJsonObject candidate = value.toObject();
            if (candidate.value(QStringLiteral("draft")).toBool())
                continue;
            const QString tag = candidate.value(QStringLiteral("tag_name")).toString();
            if (tag.isEmpty())
                continue;
            if (release.isEmpty()
                || version_compare(release.value(QStringLiteral("tag_name"))
                                       .toString().toUtf8().constData(),
                                   tag.toUtf8().constData()) < 0)
                release = candidate;
        }
    }
    if (release.isEmpty()) {
        fail(QStringLiteral("update.errResponse"));
        return;
    }
    latestVersion_ = release.value(QStringLiteral("tag_name")).toString();
    updateLog(QStringLiteral("check: latest is ") + latestVersion_);
    if (latestVersion_.isEmpty()) {
        fail(QStringLiteral("update.errResponse"));
        return;
    }

    const QJsonArray assets = release.value(QStringLiteral("assets")).toArray();
    for (const QJsonValue &value : assets) {
        const QJsonObject asset = value.toObject();
        if (asset.value(QStringLiteral("name")).toString()
            != QLatin1String(kAssetName))
            continue;
        assetUrl_ = asset.value(QStringLiteral("browser_download_url")).toString();
        assetSize_ = qint64(asset.value(QStringLiteral("size")).toDouble());
        break;
    }

    if (version_compare(APP_VERSION,
                        latestVersion_.toUtf8().constData()) >= 0) {
        publish(QStringLiteral("uptodate"));
        return;
    }
    if (assetUrl_.isEmpty()) {
        /* A newer release exists but ships no binary we can install. */
        fail(QStringLiteral("update.errNoAsset"));
        return;
    }
    publish(QStringLiteral("available"));
}

void Updater::install()
{
    if (assetUrl_.isEmpty())
        return;
    updateLog(QStringLiteral("install: ") + assetUrl_);

    errorKey_.clear();
    errorDetail_.clear();
    publish(QStringLiteral("downloading"));

    if (!inkViewNetworkUp()) {
        fail(QStringLiteral("update.errNoNetwork"));
        return;
    }

    const QString zipPath = updatePath(kAssetName);
    if (!download(assetUrl_, zipPath, kDownloadTimeoutSeconds, true))
        return;

    const qint64 got = QFileInfo(zipPath).size();
    if (got == 0 || (assetSize_ > 0 && got != assetSize_)) {
        QFile::remove(zipPath);
        fail(QStringLiteral("update.errCorrupt"));
        return;
    }

    /* Stage next to the installed binary: mv is only atomic within one mount. */
    const QString staged = appFilePath() + QStringLiteral(".new");
    updateLog(QStringLiteral("install: unpacking to ") + staged);
    if (!unpack(zipPath, staged)) {
        QFile::remove(zipPath);
        QFile::remove(staged);
        fail(QStringLiteral("update.errCorrupt"));
        return;
    }
    QFile::remove(zipPath);

    if (!looksLikeElf(staged) || QFileInfo(staged).size() < kMinBinarySize) {
        QFile::remove(staged);
        fail(QStringLiteral("update.errCorrupt"));
        return;
    }
    QFile::setPermissions(staged,
                          QFileDevice::ReadOwner | QFileDevice::WriteOwner
                              | QFileDevice::ExeOwner | QFileDevice::ReadGroup
                              | QFileDevice::ExeGroup | QFileDevice::ReadOther
                              | QFileDevice::ExeOther);

    updateLog(QStringLiteral("install: staged, handing over"));
    if (!launchHandover(staged)) {
        /* The download is fine, only the swap failed — leave the staged file
         * so it can still be copied over by hand from a computer. */
        fail(QStringLiteral("update.errHandover"), staged);
        return;
    }
    publish(QStringLiteral("ready"));

    /* And now get out of the way. The handover script polls for this process
     * to disappear before it swaps the binary, once a second for thirty — and
     * we used to sit there waiting for the user to close the app, so the swap
     * happened on the timeout. That is where the ~25 s after an update came
     * from. Quitting on our own turns it into about a second; the delay lets
     * the "ready" line reach the panel first — a full e-ink refresh is close
     * to a second by itself, so the wait is two. */
    updateLog(QStringLiteral("install: quitting for the handover"));
    QTimer::singleShot(2000, qApp, &QCoreApplication::quit);
}

bool Updater::unpack(const QString &zip, const QString &dest)
{
    mz_zip_archive archive;
    memset(&archive, 0, sizeof(archive));
    if (!mz_zip_reader_init_file(&archive, zip.toUtf8().constData(), 0))
        return false;

    bool ok = false;
    const mz_uint count = mz_zip_reader_get_num_files(&archive);
    for (mz_uint i = 0; i < count; i++) {
        mz_zip_archive_file_stat entry;
        if (!mz_zip_reader_file_stat(&archive, i, &entry))
            continue;
        /* The release zip holds a single PocketBookStatistics.app at its root, but accept
         * it under a directory too so the packaging step can change. */
        const QString name = QString::fromUtf8(entry.m_filename);
        if (!name.endsWith(QLatin1String("PocketBookStatistics.app")))
            continue;
        ok = mz_zip_reader_extract_to_file(&archive, i,
                                           dest.toUtf8().constData(), 0);
        break;
    }

    mz_zip_reader_end(&archive);
    return ok;
}

bool Updater::launchHandover(const QString &staged)
{
    const QString scriptPath = updatePath("apply.sh");
    QFile script(scriptPath);
    if (!script.open(QIODevice::WriteOnly | QIODevice::Truncate))
        return false;
    const QByteArray body = handoverScript(appFilePath(), staged).toUtf8();
    const bool written = script.write(body) == body.size() && script.flush();
    script.close();
    if (!written)
        return false;

    /* The script waits for this process to exit, then moves the staged file
     * onto the installed one and starts it. A host test wants everything up to
     * that point and none of it: POCKETBOOK_STATISTICS_NO_HANDOVER stops at the
     * written script, which is the part worth reading back. */
    if (qEnvironmentVariableIsSet("POCKETBOOK_STATISTICS_NO_HANDOVER"))
        return true;
    return QProcess::startDetached(QStringLiteral("/bin/sh"), {scriptPath});
}
